backend:
  name: git-gateway
  branch: main # gałąź GitHub

media_folder: "images" # folder na obrazki
public_folder: "/images"

collections:
  - name: "aktualnosci"
    label: "Aktualności"
    folder: "_aktualnosci"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Treść", name: "body", widget: "markdown" }